org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true
android.useAndroidX=true

# Google Official Test Ad Units for Demo App
AdmobBanner = "ca-app-pub-3940256099942544/6300978111"
AdmobInterstitial = "ca-app-pub-3940256099942544/1033173712"
AdmobOpenAd = "ca-app-pub-3940256099942544/9257395921"
AdmobRewardedAd = "ca-app-pub-3940256099942544/5224354917"
AdmobNative = "ca-app-pub-3940256099942544/2247696110"
