plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.smdey.ads'
    compileSdk 37

    defaultConfig {
        minSdk 28
        targetSdk 37

        consumerProguardFiles 'proguard-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    // Material 3 Components
    api 'com.google.android.material:material:1.14.0'
    implementation 'androidx.lifecycle:lifecycle-process:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.11.0'

    // Google Mobile Ads & UMP SDK
    api 'com.google.android.gms:play-services-ads:25.4.0'
    api 'com.google.android.ump:user-messaging-platform:4.0.0'

    // Facebook Shimmer (for Banner Skeleton)
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.3bdesamad'
                artifactId = 'smdey-ads-sdk'
                version = '1.0.0'
            }
        }
    }
}
